### ISSUE TITLE
Feature request: webgl2 support

### ISSUE THREAD

**Issue by atorstling** [mateuszmigas/webgl-shader-viewer#7]
Hi! Great project! Would it be possible to get webgl2 and GLSL ES 3.00 shader support? (https://stackoverflow.com/a/59777271/83741)

**Comment by mateuszmigas** [comment]
Hi, thanks I think it's a good idea. I checked and it looks like vscode webview supports webgl2. I will have to verify a few things first but I will add it if possible. I see it as another dropdown (webgl/webgl2) above the shaders dropdowns.

**Comment by mateuszmigas** [comment]
Added experimental webgl2 support in latest version 0.10.0. It can be enabled via settings in vscode:

`"webglShaderViewer.renderingContext": "WebGL2"`

Adding an extra dropdown with WebGL version was quite problematic. It would require to recreate context + canvas or have two canvases around because the browser would keep some internal state attached to the canvas once a context has been created for it.
